name = "Miladycraft_1.5"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aac5b12c0b6c22090d463aa13d4ddbe94977eb317d9c4490d1481c17ac524edf"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
