name = "Miladycraft"
version = "1.6.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c56fad86d26c138b95076549676bfedf16a63f7e41d9794a74996cd447396b4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
