name = "Miladycraft_1.5"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "975b0fc12d9457851a36650e754153a189418dde8f0dbfa4acad057b466822fa"

[versions]
forge = "43.4.0"
minecraft = "1.19.2"
