JEIEvents.hideItems( event => {
    event.hide("trafficcraft:wood_road_construction_tool")
    event.hide("trafficcraft:stone_road_construction_tool")
    event.hide("trafficcraft:iron_road_construction_tool")
    event.hide("trafficcraft:gold_road_construction_tool")
    event.hide("trafficcraft:diamond_road_construction_tool")
    event.hide("trafficcraft:netherite_road_construction_tool")

    event.hide("apotheosis:potion_charm")
    event.hide("apotheosis:diamond_mining_arrow")
    event.hide("apotheosis:iron_mining_arrow")
    event.hide("apotheosis:explosive_arrow")

    event.hide("trafficcraft:bitumen_ore")
    event.hide("trafficcraft:deepslate_bitumen_ore")

    event.hide("comforts:sleeping_bag_white")
		event.hide("comforts:sleeping_bag_orange")
		event.hide("comforts:sleeping_bag_magenta")
		event.hide("comforts:sleeping_bag_light_blue")
		event.hide("comforts:sleeping_bag_yellow")
		event.hide("comforts:sleeping_bag_lime")
		event.hide("comforts:sleeping_bag_pink")
		event.hide("comforts:sleeping_bag_gray")
		event.hide("comforts:sleeping_bag_light_gray")
		event.hide("comforts:sleeping_bag_cyan")
		event.hide("comforts:sleeping_bag_purple")
		event.hide("comforts:sleeping_bag_blue")
		event.hide("comforts:sleeping_bag_brown")
		event.hide("comforts:sleeping_bag_green")
		event.hide("comforts:sleeping_bag_red")
		event.hide("comforts:sleeping_bag_black")
    
  })