# Specifies the list of sidebars that should be disabled/enabled when the recipe book button is pressed. Only works when TOGGLE mode is enabled. Supported values: index, craftables, favorites, lookup-history, craft-history, chess. If none of the values are specified, clicking the recipe book button will disable the entire EMI UI. Even though all sidebars are listed here, EMI itself may prevent some its UI elements from being disabled.
toggleableSidebars:
- craftables
