#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Feb 13 19:11:42 CET 2024
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
