# This is the configuration file for Sodium Extra.
# This file exists for debugging purposes and should not be configured otherwise.
#
# You can find information on editing this file and all the available options here:
# https://github.com/FlashyReese/sodium-extra-fabric/wiki/Configuration-File
#
# By default, this file will be empty except for this notice.
mixin.adaptive_sync=false
mixin.animation=false
mixin.biome_colors=false
mixin.cloud=false
mixin.fog=false
mixin.fog_falloff=false
mixin.gui=false
mixin.instant_sneak=false
mixin.light_updates=false
mixin.particle=false
mixin.prevent_shaders=false
mixin.reduce_resolution_on_mac=true
mixin.render=false
mixin.render.block=false
mixin.render.block.entity=false
mixin.render.entity=false
mixin.sky=false
mixin.sky_colors=false
mixin.sodium=false
mixin.sodium.accessibility=false
mixin.sodium.biome_blend=false
mixin.sodium.resolution=false
mixin.sodium.scrollable_page=false
mixin.sodium.vsync=false
mixin.stars=false
mixin.sun_moon=false
mixin.toasts=false