
[trafficcraft_common_config]

	[trafficcraft_common_config.world_generation]
		#Min generation height for bitumen ore. Default: 55 blocks
		bitumen_ore_min_height = 55
		#Max generation height for bitumen ore. Default: 75 blocks
		bitumen_ore_max_height = 75
		#How common bitumen ore will be generated in each chunk. Default: 2
		bitumen_ore_rarity = 0
		#Max size of bitumen ore veins. Default: 25
		bitumen_ore_vein_size = 0

	[trafficcraft_common_config.road_construction_tool]
		#The max distance in blocks the road construction tool can be used for. Default: 32 blocks
		#Range: 0 ~ 64
		max_distance = 0
		#Max width of roads built by the road construction tool. Default: 9 blocks.
		#Range: 1 ~ 15
		max_width = 1
		#Max slope of roads built by the road construction tool. Default: 4.0
		max_slope = 4.0

